### ISSUE TITLE
I can contribute to the docs for this. Just need to learn how to do so

### ISSUE THREAD

**Issue by simkimsia** [CakeDC/Enum#12]
I am happy to contribute the docs. 

I only need some briefing on : 
1. what does this Enum roughly do?
2. how do I create the .rst files and get it up on readthedocs.org?

I can be on the irc channe #cakephp or #FriendsOfCakel. And we can talk this through.

**Comment by steinkel** [comment]
Thank you!

Would be maybe better to work on an initial doc about using the plugin first and then let you improve it via examples, etc, let me assign this and we'll handle it. Thank you

**Comment by simkimsia** [comment]
Cool @steinkel How do we start?

**Comment by steinkel** [comment]
I've assigned ticket to @pmoraes he'll be preparing some basic docs for the plugin and we can continue from there...

**Comment by steinkel** [comment]
Hey @simkimsia we merged initial documentation under https://github.com/CakeDC/Enum/blob/master/Docs/Home.md please take a look and feel free to contribute :+1: Check http://www.cakedc.com/plugin-standard#documentation for our documentation standards, thank you!
