### ISSUE TITLE
Enum Helper

### ISSUE THREAD

**Issue by Ali1** [CakeDC/Enum#13]
Would having an emum helper to pull the enum configuration into a view be useful or is there a better way of doing this?

**Comment by Ali1** [comment]
Currently using:
`$LeadsTable = new App\Model\Table\LeadsTable;`
`echo $this->Form->input('type', ['options' => $LeadsTable->enum('type')]);`

**Comment by pmoraes** [comment]
Hello @Ali1 , could you take a look in the #16 pull request? There is the documentation showing the best way to solve your problem.

**Comment by pmoraes** [comment]
@Ali1  any doubts yet?

**Comment by steinkel** [comment]
Please reopen if more feedback required, thanks!
