### ISSUE TITLE
Enum translation

### ISSUE THREAD

**Issue by forstjiri** [CakeDC/Enum#19]
Is it possible to use different name for saving and displaying for multilingual purposes?

**Comment by pmoraes** [comment]
Hi @aiphee it does not support yet.

**Comment by inoas** [comment]
A strategy like privateArray would help with that as constant values cannot easily be translated.

**Comment by ADmad** [comment]
Adding translation support would be easy. You could just update `EnumBehavior::enum()` to run the list values through `__()` or similar before returning.

**Comment by inoas** [comment]
When we get to use it (currently just planned), we will patch it and contribute back, if no one beats us to it. We'd probably prefer `__d()` with the domain set to the current plugin (if it is set) over `__()`.
