### ISSUE TITLE
Missing Helper?

### ISSUE THREAD

**Issue by cewi** [CakeDC/Enum#28]
[/Docs/Documentation/Configuration.md](https://github.com/CakeDC/Enum/blob/master/Docs/Documentation/Configuration.md) states to load a helper:
> $this->loadHelper('CakeDC/Enum.Enum');

My downloaded plugin doesn't include a helper.
Version v.1.0.0, installation via composer.

**Comment by pmoraes** [comment]
Hi @cewi, I was taking a look at this issue, the documentation is wrong, just need to fix the documentation, please do not use "$this->loadHelper('CakeDC/Enum.Enum');" it isn't being used anymore.

**Comment by cewi** [comment]
Thank you. I instead load the list with the enum() method in the controller and set the variable for the template, e.g.:
```
     $this->set('types', $this->Articles->enum('type'));
```
Is this the recommended way?

**Comment by pmoraes** [comment]
Hi @cewi, yes. This is the recommended way. I'll fix the documentation, so we won't more problems like that.

Do you need something more?

**Comment by cewi** [comment]
No, that's perfect for me. Thanks!
