### ISSUE TITLE
Enums not working with irregular fieldnames

### ISSUE THREAD

**Issue by inoas** [CakeDC/Enum#31]
# Problem

```php
    const SALUTATION_001 = 'Herr';
    const SALUTATION_002 = 'Frau';
    const SALUTATION_003 = 'Firma';
    const SALUTATION_004 = 'Herr und Frau';
    const SALUTATION_005 = 'Frau und Herr';
    const SALUTATION_006 = 'Frau und Frau';
    const SALUTATION_007 = 'Herr und Herr';
    const SALUTATION_008 = 'Eheleute';
    const SALUTATION_021 = 'Firma mit Ansprechpartner';
    //...
        $this->addBehavior('CakeDC/Enum.Enum', ['lists' => [
            'xml_kundendaten_adresse_anrede' => [
                'strategy' => 'const',
                'prefix' => 'SALUTATION',
                'field' => 'Xml_Kundendaten_Adresse_Anrede',
            ],
        ]]);
```

## Error

`Error CakeDC\Enum\Model\Behavior\Exception\MissingEnumConfigurationException`

# Workaround
```php
        // Note that BOTH have to be set, else it throws exceptions once in _call()  and once in enum()
        $this->addBehavior('CakeDC/Enum.Enum', ['lists' => [
            'xml_kundendaten_adresse_anrede' => [
                'strategy' => 'const',
                'prefix' => 'SALUTATION',
                'field' => 'Xml_Kundendaten_Adresse_Anrede',
            ],
            'Xml_Kundendaten_Adresse_Anrede' => [
                'strategy' => 'const',
                'prefix' => 'SALUTATION',
                'field' => 'Xml_Kundendaten_Adresse_Anrede',
            ],
        ]]);
```

# Question

Is there a reason the list keys are being inflected around inside the behavior?

**Comment by pmoraes** [comment]
Hi @inoas, I'll be taking a look at this issue, as soon as possible I'll give a better status for you. Thanks.

**Comment by pmoraes** [comment]
Hi @inoas, I was checking your code, so what you need to do is follow the cake standard, so when you set the variable from the method, you need to use camel case, you should to have something like that **_$this->set('xmlKundendatenAdresseAnredes', $this->YOUR_TABLE->enum('xml_kundendaten_adresse_anrede'));_** in your controller. You don't need to have this param **'field' => 'Xml_Kundendaten_Adresse_Anrede'**, do you need some help more about this question?

**Comment by inoas** [comment]
No I get it, however It shipped now with this code am works (tm) ;)
Next time I use CakeDC/Enum AND do not follow conventions (sorry about that, usually I do) I will try this and if it does not work will try to come up with a PR.
