### ISSUE TITLE
Problem with multi worded prefix in ConstStrategy.

### ISSUE THREAD

**Issue by ADmad** [CakeDC/Enum#4]
If you have constants like `NODE_TYPE_PAGE`, `NODE_TYPE_BLOG` etc. and you configure the behavior to use `'const' => 'node_type'`, the prefix list generated by `ConstStratgey::listPrefixes()` has `NODE` instead of `NODE_TYPE`.

Things get uglier if you have another set of constants like `NODE_FOO_BAR` and try use list with prefix `node_foo` and you get `MissingEnumStrategyPrefixException`.

**Comment by jadb** [comment]
Yup - aware of that one - haven't worked on something to resolve it yet. I'll add it as bug since it's a current limitation.

**Comment by ADmad** [comment]
In general it's not clear to me why do you try to guess/extract prefixes in strategies when the prefix that strategy is interested in is already present in config? IMHO listPrefixes() shouldn't exist at all. Each strategy is meant to provide list for just one configured prefix, so just need to check if list for the configured prefix is available.
