### ISSUE TITLE
CakePHP 3.6 Update

### ISSUE THREAD

**Issue by liviakuenzli** [CakeDC/Enum#44]
Hey :)

I noticed you have a branch ready for 3.6 support, what is missing from it so that it can be released? Can we help?

**Comment by ravage84** [comment]
@liviascapin  can you have a look if something is missing on that branch by using it in our related application, please?

**Comment by liviakuenzli** [comment]
Since the newly release version (1.4) is 3.6 compatible, I updated to 1.4 and played around for a bit, it seems to work fine.

@skie Thank you very much :blue_heart:
