### ISSUE TITLE
Error in ConstStrategy while formatig results

### ISSUE THREAD

**Issue by kaihoefler** [CakeDC/Enum#55]
I get the following error when I use the const strategy with enum:

`Cake\Utility\Hash::get(): Argument #2 ($path) must be of type array|string|int|null, Cake\ORM\Entity given, called in /application/vendor/cakedc/enum/src/Model/Behavior/Strategy/ConstStrategy.php on line 133`

The situation i experience is that while iterating through the result set of a query the $row in the beforeFind event already has been formated and is of type Cake\ORM\Entity.

I do not understand how this happens, but it can be fixed by adding the line

`if ($constant instanceof Entity) return $row;` after line 128 in the class ConstStrategy.

**Comment by arusinowski** [comment]
@kaihoefler thank you for reporting this issue. I see that you are using the `dev` version, there is stable version 3.0.0 with support for CakePHP5.0, did you tried to use this version instead?

**Comment by jayevt** [comment]
@arusinowski , It is working fine in CakePHP3 and enum package version '1.4.0'. 

But, I upgraded the project from CakePHP3 to CakePHP4. I am using version [2.1.0](https://github.com/CakeDC/Enum/tree/2.1.0) for CakePHP4 and facing the same problem. Can you fix it for CakePHP4?
