### ISSUE TITLE
Error in ConstStrategy while formatting results

### ISSUE THREAD

**Issue by jayevt** [CakeDC/Enum#57]
It is working fine in CakePHP3 and enum package version '1.4.0'. I upgraded the project from CakePHP3 to CakePHP4. I am using version [2.1.0](https://github.com/CakeDC/Enum/tree/2.1.0) for CakePHP4

I get the following error when I use the const strategy with enum:

ERROR: [InvalidArgumentException] Invalid Parameter {     "label": null,     "prefix": "TYPE",     "value": null }, should be dot separated path or array. in /var/www/html/vendor/cakephp/cakephp/src/Utility/Hash.php on line 65

It can be fixed by adding the below after line 128 in the class ConstStrategy.

`if ($constant instanceof Entity) {
      return $row;
 }`
 
 I think this issue this same as https://github.com/CakeDC/Enum/issues/55. Can you please provide support for v2.1.0.

**Comment by arusinowski** [comment]
@jay-eventrac version https://github.com/CakeDC/Enum/releases/tag/2.2.0 released, thank you for the contribution
