### ISSUE TITLE
Field with null values no longer work even set opion `allowEmpty` as true

### ISSUE THREAD

**Issue by TABTyrell** [CakeDC/Enum#63]
The option allowEmpty was introduced in https://github.com/CakeDC/Enum/pull/34

The plugin has been upgraded to support CakePHP v5. Despite the upgrade, the lines of code (LOC) remain unchanged https://github.com/CakeDC/Enum/blob/7e8ac1a7da0ab2ec839ac7c3cb9f674fb3d0048b/src/Model/Behavior/EnumBehavior.php#L295

In CakePHP v5, the `Entity::has()` changed as mentioned in [here](https://book.cakephp.org/5/en/orm/entities.html#:~:text=You%20can%20check%20if%20fields%20are%20defined%20in%20your%20entities%20with%20has()%3A)

This change caused an issue on my end where fields with `null` values triggered errors in `buildRules`. I prefer not to disable `applicationRules` to handle this scenario. Instead, it’s better to replace `!Entity::has()` with `Entity::isEmpty()` to address the problem.

**Comment by arusinowski** [comment]
@TABTyrell @Ridzuan94 the fix is released with the version https://github.com/CakeDC/Enum/releases/tag/3.1.1
